# Generated by Django 6.0.8 on 2026-10-02 13:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Beitrag (€)')),
                ('billing_interval', models.CharField(choices=[('YEARLY', 'Jährlich'), ('MONTHLY', 'Monatlich')], default='YEARLY', max_length=20, verbose_name='Abrechnungsintervall')),
                ('min_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mindestalter')),
                ('max_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Höchstalter')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Mitgliedschaftsart',
                'verbose_name_plural': 'Mitgliedschaftsarten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('status', models.CharField(choices=[('PENDING', 'Ausstehend'), ('APPROVED', 'Genehmigt'), ('REJECTED', 'Abgelehnt')], default='PENDING', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Geprüft am')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Ablehnungsgrund')),
                ('sepa_iban', models.CharField(blank=True, max_length=50, verbose_name='SEPA IBAN')),
                ('sepa_mandate_date', models.DateField(blank=True, null=True, verbose_name='SEPA Mandatsdatum')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Geprüft von')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_applications', to=settings.AUTH_USER_MODEL, verbose_name='Antragsteller')),
                ('requested_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.membershiptype', verbose_name='Gewünschte Mitgliedschaftsart')),
            ],
            options={
                'verbose_name': 'Mitgliedsantrag',
                'verbose_name_plural': 'Mitgliedsanträge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('member_number', models.CharField(max_length=30, unique=True, verbose_name='Mitgliedsnummer')),
                ('start_date', models.DateField(verbose_name='Beginn')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Enddatum')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktiv'), ('PAUSED', 'Pausiert'), ('ENDED', 'Beendet')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Mitglied')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.membershiptype', verbose_name='Mitgliedschaftsart')),
            ],
            options={
                'verbose_name': 'Mitgliedschaft',
                'verbose_name_plural': 'Mitgliedschaften',
                'ordering': ['member_number'],
            },
        ),
    ]
