# Generated by Django 6.0.8 on 2026-10-02 21:39

import apps.core.fields
from django.db import migrations


def encrypt_existing_ibans(apps, schema_editor):
    Application = apps.get_model("members", "MembershipApplication")
    for pk, value in (
        Application.objects.using(schema_editor.connection.alias)
        .values_list("pk", "sepa_iban")
        .iterator()
    ):
        if value:
            Application.objects.using(schema_editor.connection.alias).filter(
                pk=pk
            ).update(sepa_iban=value)


def decrypt_existing_ibans(apps, schema_editor):
    Application = apps.get_model("members", "MembershipApplication")
    connection = schema_editor.connection
    table = connection.ops.quote_name(Application._meta.db_table)
    with connection.cursor() as cursor:
        for pk, value in (
            Application.objects.using(connection.alias)
            .values_list("pk", "sepa_iban")
            .iterator()
        ):
            if value:
                cursor.execute(
                    f"UPDATE {table} SET sepa_iban = %s WHERE id = %s", [value, pk]
                )


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipapplication",
            name="sepa_iban",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=255, verbose_name="SEPA IBAN"
            ),
        ),
        migrations.RunPython(encrypt_existing_ibans, decrypt_existing_ibans),
    ]
