# Generated by Django 6.0.8 on 2026-10-02 21:33

import django.db.models.functions.text
from django.db import migrations, models


def check_duplicate_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    duplicates = (
        User.objects.using(schema_editor.connection.alias)
        .annotate(canonical=django.db.models.functions.text.Lower("email"))
        .values("canonical")
        .annotate(count=models.Count("pk"))
        .filter(count__gt=1)
    )
    if duplicates.exists():
        raise RuntimeError(
            "E-Mail-Adressen sind unabhängig von Groß-/Kleinschreibung mehrfach vorhanden. Bitte die betroffenen Konten vor der Migration manuell prüfen; siehe DEPLOYMENT.md."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_create_groups"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_failed_login_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(check_duplicate_emails, migrations.RunPython.noop),
        migrations.AddField(
            model_name="user",
            name="failed_login_window_started_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="accounts_user_email_ci_unique",
            ),
        ),
    ]
