# Generated by Django 6.0.9 on 2026-10-07 09:08

from django.db import migrations, models
from django.utils import timezone


def date_legacy_verification_links(apps, schema_editor):
    # Existing links get one transition window; subsequently every token is dated.
    User = apps.get_model("accounts", "User")
    User.objects.using(schema_editor.connection.alias).exclude(
        email_verification_token=""
    ).filter(email_verification_sent_at__isnull=True).update(
        email_verification_sent_at=timezone.now()
    )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_last_failed_login_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_access_sent_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="allow_partner_search",
            field=models.BooleanField(
                default=False,
                help_text="Dein Name wird anderen teilnahmeberechtigten Personen zur Partnerwahl angezeigt, bei offenen Turnieren auch Gästen.",
                verbose_name="In der Doppelpartnersuche sichtbar sein",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_sent_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(date_legacy_verification_links, migrations.RunPython.noop),
    ]
