# Generated by Django 6.0.8 on 2026-10-02 13:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=100, verbose_name='Konkurrenz')),
                ('discipline', models.CharField(choices=[('SINGLES', 'Einzel'), ('DOUBLES', 'Doppel'), ('MIXED', 'Mixed')], default='SINGLES', max_length=20, verbose_name='Disziplin')),
                ('format', models.CharField(choices=[('KNOCKOUT', 'K.-o.-System'), ('ROUND_ROBIN', 'Jeder gegen jeden'), ('GROUPS_KO', 'Gruppenphase + K.-o.')], default='KNOCKOUT', max_length=20, verbose_name='Spielsystem')),
                ('max_entries', models.PositiveIntegerField(default=16, verbose_name='Max. Teilnehmer')),
                ('age_class', models.CharField(blank=True, max_length=50, verbose_name='Altersklasse')),
            ],
            options={
                'verbose_name': 'Konkurrenz',
                'verbose_name_plural': 'Konkurrenzen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HonorRollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('year', models.PositiveIntegerField(verbose_name='Jahr')),
                ('competition_name', models.CharField(max_length=100, verbose_name='Bewerb')),
                ('winner_name', models.CharField(max_length=150, verbose_name='Ortsmeister / Sieger')),
                ('runner_up_name', models.CharField(blank=True, max_length=150, verbose_name='Zweitplatzierter')),
                ('score', models.CharField(blank=True, max_length=50, verbose_name='Finalergebnis')),
            ],
            options={
                'verbose_name': 'Ehrentafel-Eintrag',
                'verbose_name_plural': 'Ehrentafel (Ortsmeister)',
                'ordering': ['-year', 'competition_name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=150, verbose_name='Turniername')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung / Ausschreibung')),
                ('start_date', models.DateField(verbose_name='Beginn')),
                ('end_date', models.DateField(verbose_name='Ende')),
                ('registration_deadline', models.DateTimeField(verbose_name='Anmeldeschluss')),
                ('eligibility', models.CharField(choices=[('MEMBERS_ONLY', 'Nur Mitglieder'), ('MEMBERS_AND_GUESTS', 'Mitglieder und Gäste')], default='MEMBERS_ONLY', max_length=30, verbose_name='Teilnahmeberechtigung')),
                ('fee_member', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=10, verbose_name='Startgebühr Mitglieder (€)')),
                ('fee_guest', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=10, verbose_name='Startgebühr Gäste (€)')),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('OPEN', 'Anmeldung geöffnet'), ('DRAWN', 'Ausgelost'), ('RUNNING', 'Laufend'), ('FINISHED', 'Abgeschlossen')], default='DRAFT', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Turnier',
                'verbose_name_plural': 'Turniere',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('seed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Gesetzt (1, 2, ...)')),
                ('status', models.CharField(choices=[('PENDING_PARTNER', 'Wartet auf Partnerbestätigung'), ('CONFIRMED', 'Bestätigt'), ('WAITLIST', 'Warteliste'), ('WITHDRAWN', 'Zurückgezogen')], default='CONFIRMED', max_length=20, verbose_name='Status')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournaments.competition', verbose_name='Konkurrenz')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries_p1', to=settings.AUTH_USER_MODEL, verbose_name='Spieler 1')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries_p2', to=settings.AUTH_USER_MODEL, verbose_name='Spieler 2 (Partner)')),
            ],
            options={
                'verbose_name': 'Turnieranmeldung',
                'verbose_name_plural': 'Turnieranmeldungen',
                'ordering': ['competition', 'seed', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('round', models.PositiveIntegerField(default=1, verbose_name='Runde')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Position im Raster')),
                ('score', models.JSONField(blank=True, default=list, verbose_name='Ergebnis (Satzliste)')),
                ('result_type', models.CharField(choices=[('NORMAL', 'Regulär beendet'), ('RETIRED', 'Aufgabe (w.o. / ret.)'), ('WALKOVER', 'Nicht angetreten (w.o.)')], default='NORMAL', max_length=20, verbose_name='Ergebnistyp')),
                ('scheduled_start', models.DateTimeField(blank=True, null=True, verbose_name='Spieltermin')),
                ('blocking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courts.blocking', verbose_name='Zugehörige Platzsperre')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.competition', verbose_name='Konkurrenz')),
                ('entry_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_a', to='tournaments.entry', verbose_name='Spieler / Paar A')),
                ('entry_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_b', to='tournaments.entry', verbose_name='Spieler / Paar B')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_matches', to='tournaments.match', verbose_name='Nächstes Spiel im K.-o.-Baum')),
                ('scheduled_court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courts.court', verbose_name='Angesetzter Platz')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='tournaments.entry', verbose_name='Sieger')),
            ],
            options={
                'verbose_name': 'Match / Spiel',
                'verbose_name_plural': 'Matches',
                'ordering': ['competition', 'round', 'position'],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='tournaments.tournament', verbose_name='Turnier'),
        ),
    ]
