# Generated by Django 6.0.8 on 2026-10-02 13:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriename')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'News-Kategorie',
                'verbose_name_plural': 'News-Kategorien',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('teaser', models.TextField(blank=True, verbose_name='Teaser / Vorschautext')),
                ('body', models.TextField(verbose_name='Inhalt (HTML)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/covers/', verbose_name='Titelbild')),
                ('cover_image_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt-Text für Titelbild')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Öffentlich'), ('MEMBERS', 'Nur Mitglieder')], default='PUBLIC', max_length=20, verbose_name='Sichtbarkeit')),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('PUBLISHED', 'Veröffentlicht'), ('ARCHIVED', 'Archiviert')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Veröffentlichungsdatum')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Oben anheften (Sticky)')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['-is_pinned', '-publish_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('image', models.ImageField(upload_to='news/gallery/large/', verbose_name='Originalbild (Groß)')),
                ('image_medium', models.ImageField(blank=True, upload_to='news/gallery/medium/', verbose_name='Mittelgroßes Bild')),
                ('image_thumb', models.ImageField(blank=True, upload_to='news/gallery/thumbs/', verbose_name='Vorschaubild (Thumbnail)')),
                ('alt_text', models.CharField(max_length=255, verbose_name='Alt-Text')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Bildunterschrift')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='news.article', verbose_name='Artikel')),
            ],
            options={
                'verbose_name': 'Galeriebild',
                'verbose_name_plural': 'Galeriebilder',
                'ordering': ['order', 'id'],
            },
        ),
    ]
