# Generated by Django 6.0.8 on 2026-10-02 13:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('price_member', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preis für Mitglieder (€)')),
                ('price_guest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preis für Gäste (€)')),
                ('unit', models.CharField(choices=[('PER_HOUR', 'Pro Stunde'), ('PER_BOOKING', 'Pro Buchung')], default='PER_HOUR', max_length=20, verbose_name='Abrechnungseinheit')),
                ('mode', models.CharField(choices=[('AUTOMATIC', 'Automatisch (z.B. Halle)'), ('OPTIONAL', 'Optional wählbar (z.B. Flutlicht)')], default='OPTIONAL', max_length=20, verbose_name='Modus')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('courts', models.ManyToManyField(blank=True, related_name='extras', to='courts.court', verbose_name='Gültig für Plätze (leer = alle)')),
            ],
            options={
                'verbose_name': 'Buchungs-Extra',
                'verbose_name_plural': 'Buchungs-Extras',
            },
        ),
        migrations.CreateModel(
            name='BookingExtraLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='Menge')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis (€) [eingefroren]')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gesamtbetrag (€)')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_lines', to='courts.booking', verbose_name='Buchung')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.bookingextra', verbose_name='Extra')),
            ],
            options={
                'verbose_name': 'Buchungs-Extra-Posten',
                'verbose_name_plural': 'Buchungs-Extra-Posten',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('kind', models.CharField(choices=[('MEMBERSHIP_FEE', 'Mitgliedsbeitrag'), ('COURT_FEE', 'Platzgebühr'), ('GUEST_FEE', 'Gastgebühr'), ('TOURNAMENT_FEE', 'Turnier-Startgebühr'), ('OTHER', 'Sonstige Gebühr')], default='OTHER', max_length=30, verbose_name='Art')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Gesamtbetrag (€)')),
                ('due_date', models.DateField(verbose_name='Fälligkeitsdatum')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Periode von')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Periode bis')),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('PARTIAL', 'Teilweise bezahlt'), ('PAID', 'Bezahlt'), ('WAIVED', 'Erlassen'), ('CANCELLED', 'Storniert')], default='OPEN', max_length=20, verbose_name='Zahlungsstatus')),
                ('description', models.CharField(max_length=255, verbose_name='Verwendungszweck / Beschreibung')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('dunning_level', models.PositiveIntegerField(default=0, verbose_name='Mahnstufe')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Forderung',
                'verbose_name_plural': 'Forderungen',
                'ordering': ['-due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Zahlbetrag (€)')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bezahlt am')),
                ('method', models.CharField(choices=[('TRANSFER', 'Überweisung'), ('SEPA', 'SEPA-Lastschrift'), ('CASH', 'Barzahlung')], default='TRANSFER', max_length=20, verbose_name='Zahlungsmethode')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Zahlungsreferenz / Belegnummer')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.charge', verbose_name='Forderung')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='Erfasst von')),
            ],
            options={
                'verbose_name': 'Zahlung',
                'verbose_name_plural': 'Zahlungen',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('applies_to', models.CharField(choices=[('MEMBER', 'Mitglied'), ('GUEST', 'Gast'), ('GUEST_OF_MEMBER', 'Gast eines Mitglieds')], default='GUEST', max_length=30, verbose_name='Gilt für')),
                ('weekday_mask', models.CharField(default='1111111', max_length=7, verbose_name='Wochentage-Maske (Mo-So: 1111111)')),
                ('time_from', models.TimeField(blank=True, null=True, verbose_name='Gültig ab Uhrzeit')),
                ('time_to', models.TimeField(blank=True, null=True, verbose_name='Gültig bis Uhrzeit')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preis pro Stunde (€)')),
                ('price_per_person', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preis pro Person/Gast (€)')),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='courts.court', verbose_name='Platz (leer = alle Plätze)')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rules', to='courts.season', verbose_name='Saison (optional)')),
            ],
            options={
                'verbose_name': 'Preisregel',
                'verbose_name_plural': 'Preisregeln',
            },
        ),
    ]
