# Generated by Django 6.0.8 on 2026-10-02 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TC Musterdorf', max_length=150, verbose_name='Vereinsname')),
                ('short_name', models.CharField(default='TCM', max_length=20, verbose_name='Kürzel')),
                ('tagline', models.CharField(default='Spiel, Satz und Verein.', max_length=255, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club/', verbose_name='Logo')),
                ('email', models.EmailField(default='kontakt@tc-musterdorf.at', max_length=254, verbose_name='Kontakt E-Mail')),
                ('phone', models.CharField(blank=True, default='+43 123 456789', max_length=50, verbose_name='Telefon')),
                ('address', models.TextField(default='Tennisweg 1, 1234 Musterdorf', verbose_name='Adresse')),
                ('bank_name', models.CharField(default='Musterbank', max_length=100, verbose_name='Bankname')),
                ('iban', models.CharField(default='AT000000000000000000', max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(default='MUSTAT2X', max_length=11, verbose_name='BIC')),
                ('payment_reference_prefix', models.CharField(default='TCM-', max_length=20, verbose_name='Zahlungsreferenz-Präfix')),
                ('imprint_text', models.TextField(default='<h2>TC Musterdorf</h2><p>ZVR-Zahl: 123456789</p><p>Vertreten durch den Vorstand.</p>', verbose_name='Impressum (HTML/Text)')),
                ('privacy_text', models.TextField(default='<h2>Datenschutzerklärung</h2><p>Wir verarbeiten personenbezogene Daten nach DSGVO Art. 6.</p>', verbose_name='Datenschutzerklärung (HTML/Text)')),
                ('advance_days_member', models.PositiveIntegerField(default=7, verbose_name='Max. Vorlauf Mitglieder (Tage)')),
                ('advance_days_guest', models.PositiveIntegerField(default=2, verbose_name='Max. Vorlauf Gäste (Tage)')),
                ('max_open_bookings', models.PositiveIntegerField(default=2, verbose_name='Max. offene Buchungen pro Mitglied')),
                ('max_duration_minutes', models.PositiveIntegerField(default=120, verbose_name='Max. Dauer pro Buchung (Min.)')),
                ('free_cancel_hours', models.PositiveIntegerField(default=4, verbose_name='Kostenlose Stornierung bis X Std. vorher')),
                ('prorated_membership_fees', models.BooleanField(default=True, verbose_name='Anteilige Beitragsberechnung bei unterjährigem Eintritt')),
            ],
            options={
                'verbose_name': 'Vereinseinstellungen',
                'verbose_name_plural': 'Vereinseinstellungen',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Aktion')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Entitätstyp')),
                ('entity_id', models.CharField(max_length=100, verbose_name='Entitäts-ID')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Änderungen / Details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Zeitstempel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Änderungsprotokoll',
                'verbose_name_plural': 'Änderungsprotokolle',
                'ordering': ['-created_at'],
            },
        ),
    ]
