# Generated by Django 6.0.9 on 2026-10-07 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_clubsettings_offline_emergency_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutgoingEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("from_email", models.EmailField(max_length=254)),
                ("recipients", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ausstehend"),
                            ("SENT", "Versendet"),
                            ("FAILED", "Versand fehlgeschlagen"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "E-Mail-Versandauftrag",
                "verbose_name_plural": "E-Mail-Versandaufträge",
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="outgoing_email_due_idx",
                    )
                ],
            },
        ),
    ]
