# Generated by Django 6.0.8 on 2026-10-02 13:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=50, verbose_name='Platzname')),
                ('surface', models.CharField(choices=[('SAND', 'Sandplatz'), ('HARTPLATZ', 'Hartplatz'), ('HALLE', 'Teppich / Halle'), ('RASEN', 'Rasen')], default='SAND', max_length=20, verbose_name='Belag')),
                ('is_indoor', models.BooleanField(default=False, verbose_name='Halle / Indoor')),
                ('has_floodlight', models.BooleanField(default=False, verbose_name='Flutlicht vorhanden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Platz',
                'verbose_name_plural': 'Plätze',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=100, verbose_name='Saisonname')),
                ('start_date', models.DateField(verbose_name='Saisonbeginn')),
                ('end_date', models.DateField(verbose_name='Saisonende')),
            ],
            options={
                'verbose_name': 'Saison',
                'verbose_name_plural': 'Saisons',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('start', models.DateTimeField(verbose_name='Beginn')),
                ('end', models.DateTimeField(verbose_name='Ende')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Bestätigt'), ('CANCELLED', 'Storniert')], default='CONFIRMED', max_length=20, verbose_name='Status')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Storniert am')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Gesamtpreis (€)')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Gebucht von')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='courts.court', verbose_name='Platz')),
            ],
            options={
                'verbose_name': 'Buchung',
                'verbose_name_plural': 'Buchungen',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='BookingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('guest_name', models.CharField(blank=True, max_length=100, verbose_name='Gastname (falls kein Benutzerkonto)')),
                ('is_guest', models.BooleanField(default=False, verbose_name='Ist Gast')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='courts.booking', verbose_name='Buchung')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Mitspieler',
                'verbose_name_plural': 'Mitspieler',
            },
        ),
        migrations.CreateModel(
            name='Blocking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('start', models.DateTimeField(verbose_name='Beginn')),
                ('end', models.DateTimeField(verbose_name='Ende')),
                ('reason', models.CharField(choices=[('TRAINING', 'Training'), ('TEAM_MATCH', 'Mannschaftsspiel'), ('TOURNAMENT', 'Turnier'), ('MAINTENANCE', 'Platzpflege / Wartung'), ('WEATHER', 'Wetterbedingt gesperrt')], default='TRAINING', max_length=20, verbose_name='Grund')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Bemerkung / Anmerkung')),
                ('recurrence_rule', models.CharField(blank=True, max_length=100, verbose_name='Wiederholung (z.B. WEEKLY)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockings', to='courts.court', verbose_name='Platz')),
            ],
            options={
                'verbose_name': 'Platzsperre',
                'verbose_name_plural': 'Platzsperren',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('weekday', models.IntegerField(choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag'), (5, 'Samstag'), (6, 'Sonntag')], verbose_name='Wochentag')),
                ('open_time', models.TimeField(verbose_name='Öffnet um')),
                ('close_time', models.TimeField(verbose_name='Schließt um')),
                ('slot_minutes', models.PositiveIntegerField(default=60, verbose_name='Slot-Dauer (Minuten)')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='courts.court', verbose_name='Platz')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_hours', to='courts.season', verbose_name='Saison (optional)')),
            ],
            options={
                'verbose_name': 'Öffnungszeit',
                'verbose_name_plural': 'Öffnungszeiten',
                'ordering': ['weekday', 'open_time'],
            },
        ),
    ]
